#!/usr/bin/perl


sub usage
{
	print "pam-enroll <user> [device]\n";
	exit;
}


my $user = shift || usage();
my $device = shift || "/dev/hidraw0";

if (!defined getpwnam($user)) {
	print "Invalid username!\n\n";
	exit;
}

mkdir("/etc/u2f", 0755);
mkdir("/etc/u2f/keys/", 0755);

print "Remove token <ENTER>\n";
<>;
print "Insert token of user '$user' and press token-button if available. Then <ENTER>\n";
<>;

exec("u2f-enroll", "-i", $device, "-o", "/etc/u2f/keys/_".$user);


